server:
  port: 2200

spring:
#  application:
#    name: CalculatorServer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: xuanyu
    password: xuanyu

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    healthcheck:
      enabled: true
    #serviceUrl:
    #  defaultZone: http://127.0.0.1:1100/eureka/